development: &development
  adapter: postgresql
  database: appname_development
  encoding: utf8
test:
  <<: *development
  database: appname_test
production:
  <<: *development
  database: appname_production
staging:
  <<: *development
  database: appname_staging
