development: &development
  adapter: postgresql
  database: GenuineBlue_development
  encoding: utf8
test:
  <<: *development
  database: GenuineBlue_test
production:
  <<: *development
  database: GenuineBlue_production
staging:
  <<: *development
  database: GenuineBlue_staging
